---
title: "Newton Raphson Assignment"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r function}
NewtonRaphson <- function(func, StartingValue,Tolerance,MaxNumberOfIterations){
  Deviation <- func(StartingValue)[1]
  i <- 0
  newX <- StartingValue
  val <- data.frame(i = NULL, x = NULL, y= NULL)
  while ((i < MaxNumberOfIterations) && (Deviation > Tolerance)) {
    tmp <- func(newX)
    val[i + 1, 1:3] <- c(i + 1, newX, tmp[1])
    if ((tmp[1]=="NaN") || (tmp[2]=="NaN")) {
      cat("Function or derivative not defined error.")
      cat("\n", newX, tmp)
      break
    }
    newX <- newX - tmp[1]/tmp[2]
    newVal <- func(newX)
    Deviation <- abs(newVal[1])
    i <- i + 1
    cat(paste("\nIteration ", i, ":   X=", newX,"  Y=", newVal))
  }
  if (Deviation < Tolerance) {
    cat(paste("\nFound the root point: ", newX, " after ", i, "iterations"))
  } else {
    cat(paste("\nConvergence failure. Deviation: ", Deviation, "after ", i,	"iterations"))}    
  return(val)
}
```

## Function 1

$f(x) = 10x^2 +3x - 4$


```{r function1}
f1 <- function(x) {
  return(c(10*x**2 + 3*x - 4, 20*x +3))
}

a <- NewtonRaphson(f1, 10, 1e-3, 40)
curve(10*x**2 + 3*x -4, -1, 10)
for(i in 1:(nrow(a) - 1)) {
  segments(x0 = a[i, 2], y0 = a[i, 3], x1 = a[i + 1, 2], y1 = a[i + 1, 3], col = "blue", lty = 2)
}
abline(h=0)
dev.off()
```

## Function 2

$f(x) = (x-2)^3 - 6x$


```{r function2}
f2 <- function(x) {
  return(c((x - 2)**3 - 6*x, 3*(x - 2)**2 - 6))
}

a <- NewtonRaphson(f2, 10, 1e-3, 40)
curve((x - 2)**3 - 6*x, 4, 10)
for(i in 1:(nrow(a) - 1)) {
  segments(x0 = a[i, 2], y0 = a[i, 3], x1 = a[i + 1, 2], y1 = a[i + 1, 3], col = "blue", lty = 2)
}
abline(h=0)
dev.off()
```
